version: 0.2

phases:
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
      - ./gradlew assembleAndroidTest
artifacts:
  files:
      - './android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk'
      - './android/app/build/outputs/apk/debug/app-debug.apk'
  discard-paths: yes
